package interface_adapter.events;

import use_case.Direction;
import use_case.PlayerMovementUseCase;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JFrame;

/**
 * PlayerInputController translates raw keyboard input into movement commands.
 * 
 * Responsibilities:
 * - Listens for key press/release events (implements KeyListener)
 * - Translates keyboard events (WASD) into domain concepts (Direction enum)
 * - Updates the PlayerMovementUseCase movement state
 * - Handles special keys (ESC to exit)
 * - Acts as a bridge between Swing input events and the application layer
 * 
 * This controller follows Clean Architecture by keeping presentation concerns
 * (KeyListener) separate from business logic (PlayerMovementUseCase).
 */
public class PlayerInputController implements KeyListener {
    
    private final PlayerMovementUseCase playerMovementUseCase;
    private JFrame parentFrame;  // Optional: for exit handling
    
    /**
     * Constructs a PlayerInputController with the given use case.
     * 
     * @param playerMovementUseCase the use case to delegate movement commands to
     */
    public PlayerInputController(PlayerMovementUseCase playerMovementUseCase) {
        this.playerMovementUseCase = playerMovementUseCase;
    }
    
    /**
     * Sets the parent frame for exit handling.
     * 
     * @param frame the parent JFrame
     */
    public void setParentFrame(JFrame frame) {
        this.parentFrame = frame;
    }
    
    /**
     * Called when a key is pressed.
     * Translates WASD keys to Direction commands and notifies the use case.
     * 
     * @param e the KeyEvent generated by the keyboard
     */
    @Override
    public void keyPressed(KeyEvent e) {
        int keyCode = e.getKeyCode();
        
        // Handle ESC to exit
        if (keyCode == KeyEvent.VK_ESCAPE) {
            if (parentFrame != null) {
                parentFrame.dispose();
                System.exit(0);
            }
            return;
        }
        
        switch (keyCode) {
            case KeyEvent.VK_W:
                playerMovementUseCase.setMovementState(Direction.UP, true);
                break;
            case KeyEvent.VK_A:
                playerMovementUseCase.setMovementState(Direction.LEFT, true);
                break;
            case KeyEvent.VK_S:
                playerMovementUseCase.setMovementState(Direction.DOWN, true);
                break;
            case KeyEvent.VK_D:
                playerMovementUseCase.setMovementState(Direction.RIGHT, true);
                break;
        }
    }
    
    /**
     * Called when a key is released.
     * Translates WASD key releases to Direction commands and notifies the use case.
     * 
     * @param e the KeyEvent generated by the keyboard
     */
    @Override
    public void keyReleased(KeyEvent e) {
        int keyCode = e.getKeyCode();
        
        switch (keyCode) {
            case KeyEvent.VK_W:
                playerMovementUseCase.setMovementState(Direction.UP, false);
                break;
            case KeyEvent.VK_A:
                playerMovementUseCase.setMovementState(Direction.LEFT, false);
                break;
            case KeyEvent.VK_S:
                playerMovementUseCase.setMovementState(Direction.DOWN, false);
                break;
            case KeyEvent.VK_D:
                playerMovementUseCase.setMovementState(Direction.RIGHT, false);
                break;
        }
    }
    
    /**
     * Called when a key is typed (pressed and released).
     * Not used for movement. keyPressed and keyReleased are sufficient.
     * 
     * @param e the KeyEvent generated by the keyboard
     */
    @Override
    public void keyTyped(KeyEvent e) {
        // Not used for movement. keyPressed and keyReleased are sufficient.
    }
}
